apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: boutique-image-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: "boutique-*"

      commonUpdateSettings:
        updateStrategy: "newest-build"
        allowTags: "regexp:^sha-[a-f0-9]{7,40}$"

      images:
        - alias: adservice
          imageName: ghcr.io/sulav02/adservice

        - alias: cartservice
          imageName: ghcr.io/sulav02/cartservice

        - alias: checkoutservice
          imageName: ghcr.io/sulav02/checkoutservice

        - alias: currencyservice
          imageName: ghcr.io/sulav02/currencyservice

        - alias: emailservice
          imageName: ghcr.io/sulav02/emailservice

        - alias: frontend
          imageName: ghcr.io/sulav02/frontend

        - alias: paymentservice
          imageName: ghcr.io/sulav02/paymentservice

        - alias: productcatalogservice
          imageName: ghcr.io/sulav02/productcatalogservice

        - alias: recommendationservice
          imageName: ghcr.io/sulav02/recommendationservice

        - alias: shippingservice
          imageName: ghcr.io/sulav02/shippingservice

        - alias: loadgenerator
          imageName: ghcr.io/sulav02/loadgenerator

